# Generated by Django 3.1.3 on 2021-04-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210407_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='venue',
            name='web_address',
            field=models.URLField(blank=True, max_length=120),
        ),
    ]
